export const AUTH = 'AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const AUTH_WITH_TOKEN = 'AUTH_WITH_TOKEN';
export const AUTH_WITH_TOKEN_SUCCESS = 'AUTH_WITH_TOKEN_SUCCESS';
export const AUTH_WITH_TOKEN_ERROR = 'AUTH_WITH_TOKEN_ERROR';
